server:
  port: 20002
spring:
  application:
    name: mate-admin
#数据源配置
  datasource:
    url: ${mate.datasource.url}
    username: ${mate.datasource.username}
    password: ${mate.datasource.password}
