server:
  port: 40001
spring:
  application:
    name: @artifactId@
  cloud:
    stream:
      bindings:
        log_input:
          destination: mate_log
        log_output:
          destinations: mate_log
      default-binder: kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log_consumer
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      client-id: log_producer