server:
  port: 10001
spring:
  application:
    name: @artifactId@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true
mate:
  route:
    config:
      data-id: mate-gateway-router
      group: DEFAULT_GROUP
  request:
    isTraceId: true
    isGetIp: true
    enhance: true