server:
  port: 9100
spring:
  application:
    name: mate-oauth
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234
      registered-redirect-uri: http://mrbird.cc
