spring:
  cloud:
    stream:
      bindings:
        sms-output:
          destination: sms-topic
          content-type: application/json
        sms-input:
          destination: sms-topic
          content-type: text/plain
          group: sms-group
        email-output:
          destination: email-topic
          content-type: application/json
        email-input:
          destination: email-topic
          content-type: text/plain
          group: email-group
      rocketmq:
        bindings:
          sms-output:
            producer:
              group: sms-binder-group
              sync: true
          sms-input:
            consumer:
              orderly: true
          email-output:
            producer:
              group: email-binder-group
              sync: true
          email-input:
            consumer:
              orderly: true
          binder:
            name-server: 127.0.0.1:9876

